In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/heart-disease-prediction/__results__.html
/kaggle/input/heart-disease-prediction/__resultx__.html
/kaggle/input/heart-disease-prediction/__notebook__.ipynb
/kaggle/input/heart-disease-prediction/__output__.json
/kaggle/input/heart-disease-prediction/custom.css
/kaggle/input/heart-disease-prediction/__results___files/__results___146_0.png
/kaggle/input/heart-disease-prediction/__results___files/__results___47_0.png
/kaggle/input/heart-disease-prediction/__results___files/__results___36_0.png
/kaggle/input/heart-disease-prediction/__results___files/__results___77_0.png
/kaggle/input/heart-disease-prediction/__results___files/__results___32_0.png
/kaggle/input/heart-disease-prediction/__results___files/__results___42_0.png
/kaggle/input/heartcsv/heart.csv


### If you have structured data use ensemble learning and in case of unstructured 
### data use deep learning or transfer learning 

In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("arezaei81/heartcsv")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/heartcsv


In [4]:
heart_disease = pd.read_csv("/kaggle/input/heartcsv/heart.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [5]:
# No entry is empty 
heart_disease.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [6]:
x = heart_disease.drop("target" , axis=1)
y = heart_disease["target"]

In [7]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2)

In [8]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(x_train , y_train)

RandomForestClassifier()

In [9]:
model.score(x_test , y_test)

0.819672131147541

# Trying with a different model/estimator

In [10]:
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB()

clf.fit(x_train , y_train)

GaussianNB()

In [11]:
clf.score(x_test , y_test)

0.8360655737704918

# Linear SVC 

In [12]:
# from sklearn.svm import LinearSVC 

# clf = LinearSVC()
# clf.fit(x_train , y_train)

# clf.score(x_test , y_test)

### Make predictions using a machine learning model 

2 ways to make predictions:
1. `predict`
2. `predict_proba`

In [13]:
# use a trained model to make predictions 
y_preds = clf.predict(x_test)
np.array(y_test) 

array([0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0])

In [14]:
y_test = np.array(y_test)
y_test

array([0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0])

In [15]:
# this is the same thing as clf.score 
np.mean(y_test == y_preds)

0.8360655737704918

In [16]:
# One more way to check the accuracy 
from sklearn.metrics import accuracy_score 
accuracy_score(y_test , y_preds)

0.8360655737704918

### Make prediction with `predict_proba`

predict_proba tells you the model’s confidence for each class, and the predicted class is simply the one with the highest probability.

In [17]:
# predict_proba returns probabilities of a classification label 

clf.predict_proba(x_test[:5])

array([[0.99419662, 0.00580338],
       [0.93497122, 0.06502878],
       [0.94535973, 0.05464027],
       [0.0991631 , 0.9008369 ],
       [0.9978393 , 0.0021607 ]])

In [18]:
clf.predict(x_test[:5])

array([0, 0, 0, 1, 0])